# This file contains configuration flags to customize your site

# Site settings
name: Dr. Jordan Terry
author_name: "J. K. Terry"
email: jordan@jkterry.ai
url: "https://jkterry.ai/"
baseurl: ''
description: "Dr. Jordan Terry leads the Farama Foundation, developing open-source reinforcement learning software."

# Social links
github: "https://github.com/jkterry1"
youtube: "https://www.youtube.com/channel/UC0bLGG1bmqbnm43EC4LRNIA"
linkedin: "https://www.linkedin.com/in/dr-jordan-terry/"
twitter: "https://mobile.twitter.com/j_k_terry"
google-scholar: "https://scholar.google.com/citations?user=gb83gcIAAAAJ&hl=en&oi=sra"
bluesky: "https://bsky.app/profile/j-k-terry.bsky.social"

# Analytics
# google_analytics: ""

# Build settings
markdown: kramdown
permalink: pretty
style: kjhealy

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: "jordan.jpg"
      layout: "default"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME